const crypto = require('crypto');
const pool = require('../config/database');
const AdminBalance = require('../models/AdminBalance');
const safeEqual = (a,b) => { const left=Buffer.from(String(a||'')); const right=Buffer.from(String(b||'')); return left.length===right.length && crypto.timingSafeEqual(left,right); };
const resolveSuperAdminId = () => { const configured=Number(process.env.N999BET_SUPER_ADMIN_ID); if(Number.isInteger(configured)&&configured>0)return configured; if(process.env.SUPER_ADMIN_USERNAME&&process.env.SUPER_ADMIN_PASSWORD)return 99991; return null; };
const resolveAuthorizedKey = () => process.env.SLOTOPOL_ACCESS_KEY || process.env.SLOTOPOL_ADMIN_TRANSFER_KEY;
const suppliedKey = req => req.get('X-Slotopol-Access-Key') || req.get('X-Slotopol-Transfer-Key');
exports.receiveFunding=async(req,res)=>{const expectedKey=resolveAuthorizedKey();if(!expectedKey||!safeEqual(suppliedKey(req),expectedKey))return res.status(401).json({success:false,error:'Invalid Slotopol access authorization'});const {transferId,amount,currency='MMK',countryCode='MM',description='Slotopol-admin funding'}=req.body||{};const numericAmount=Number(amount);if(!transferId||!Number.isFinite(numericAmount)||numericAmount<=0)return res.status(400).json({success:false,error:'transferId and a positive amount are required'});if(String(currency).toUpperCase()!=='MMK'||String(countryCode).toUpperCase()!=='MM')return res.status(400).json({success:false,error:'N999Bet funding is currently restricted to Myanmar MMK'});const superAdminId=resolveSuperAdminId();if(!superAdminId)return res.status(500).json({success:false,error:'Super Admin master account is not configured'});const connection=await pool.getConnection();try{await connection.beginTransaction();const [existing]=await connection.query('SELECT id FROM slotopol_funding_ledger WHERE transfer_id = ? FOR UPDATE',[String(transferId)]);if(existing.length){const [balances]=await connection.query('SELECT balance FROM admin_balances WHERE admin_id=? AND role=? LIMIT 1',[superAdminId,'super_admin']);await connection.commit();return res.json({success:true,idempotent:true,transferId:String(transferId),recipientAdminId:superAdminId,balance:Number(balances[0]?.balance||0),currency:'MMK'});}await AdminBalance.create(superAdminId,'super_admin',connection);await connection.query('INSERT INTO slotopol_funding_ledger (transfer_id,recipient_admin_id,amount,currency,country_code,description,status) VALUES (?,?,?,?,?,?,?)',[String(transferId),superAdminId,numericAmount,'MMK','MM',String(description).slice(0,500),'completed']);await connection.query('UPDATE admin_balances SET balance=balance+?,updated_at=NOW() WHERE admin_id=? AND role=?',[numericAmount,superAdminId,'super_admin']);const [balances]=await connection.query('SELECT balance FROM admin_balances WHERE admin_id=? AND role=? LIMIT 1',[superAdminId,'super_admin']);await connection.commit();return res.status(201).json({success:true,transferId:String(transferId),recipientAdminId:superAdminId,amount:numericAmount,currency:'MMK',countryCode:'MM',balance:Number(balances[0]?.balance||0)});}catch(error){await connection.rollback();console.error('Slotopol funding receive error:',error);return res.status(500).json({success:false,error:error.message||'Funding transfer failed'});}finally{connection.release();}};
exports.getFundingHistory=async(req,res)=>{try{const masterId=resolveSuperAdminId();const recipientId=req.userRole==='super_admin'&&masterId?masterId:req.userId;const [rows]=await pool.query('SELECT * FROM slotopol_funding_ledger WHERE recipient_admin_id=? ORDER BY created_at DESC LIMIT 100',[recipientId]);res.json({success:true,recipientAdminId:recipientId,funding:rows});}catch(error){res.status(500).json({success:false,error:'Failed to load funding history'});}};
exports.getMasterBalance=async(req,res)=>{try{const masterId=resolveSuperAdminId();const recipientId=req.userRole==='super_admin'&&masterId?masterId:req.userId;await AdminBalance.ensure(recipientId,req.userRole==='super_admin'?'super_admin':req.userRole||'admin');const balance=await AdminBalance.findByAdminId(recipientId);res.json({success:true,adminId:recipientId,balance:Number(balance?.balance||0),frozenBalance:Number(balance?.frozen_balance||0),currency:'MMK'});}catch(error){res.status(500).json({success:false,error:'Failed to load master balance'});}};

exports.getFundingOverview=async(req,res)=>{try{const masterId=resolveSuperAdminId();const recipientId=req.userRole==='super_admin'&&masterId?masterId:req.userId;const [balanceRows]=await pool.query('SELECT balance,frozen_balance FROM admin_balances WHERE admin_id=? LIMIT 1',[recipientId]);const [fundingRows]=await pool.query("SELECT COUNT(*) AS transferCount,COALESCE(SUM(amount),0) AS totalFunded,COALESCE(SUM(CASE WHEN DATE(created_at)=CURDATE() THEN amount ELSE 0 END),0) AS fundedToday FROM slotopol_funding_ledger WHERE recipient_admin_id=? AND status='completed'",[recipientId]);const [recentRows]=await pool.query('SELECT id,transfer_id,amount,currency,country_code,description,status,created_at FROM slotopol_funding_ledger WHERE recipient_admin_id=? ORDER BY created_at DESC LIMIT 10',[recipientId]);const b=balanceRows[0]||{};const f=fundingRows[0]||{};res.json({success:true,currency:'MMK',balance:Number(b.balance||0),frozenBalance:Number(b.frozen_balance||0),availableBalance:Number(b.balance||0)-Number(b.frozen_balance||0),transferCount:Number(f.transferCount||0),totalFunded:Number(f.totalFunded||0),fundedToday:Number(f.fundedToday||0),recentFunding:recentRows});}catch(error){console.error('Funding overview error:',error);res.status(500).json({success:false,error:'Failed to load funding overview'});}};
