import React,{createContext,useState,useEffect,useContext,useRef}from'react';
import{gameService,clearCache as clearGameCache}from'../services/gameService';
import toast from'react-hot-toast';
const GameContext=createContext();
export const useGames=()=>useContext(GameContext)||{};
const normalize=g=>{const raw=g?.raw||g||{};const enabled=g?.enabled??g?.isActive??raw.enabled??true;const category=String(g?.category||raw.category||'slots').toLowerCase();return{...raw,...g,id:String(g?.id||g?.game_id||raw.id||raw.game_id||''),name:g?.name||raw.name||'',provider:g?.provider||raw.provider||'',category,enabled,isActive:enabled!==false,status:g?.status||(enabled===false?'disabled':'active')}};
const extract=data=>{const list=Array.isArray(data)?data:data?.games||data?.list||data?.data||[];return(Array.isArray(list)?list:[]).map(normalize).filter(g=>g.id&&g.enabled!==false)};
export const GameProvider=({children})=>{const[games,setGames]=useState([]),[providers,setProviders]=useState([]),[loading,setLoading]=useState(false),[favorites,setFavorites]=useState([]),[activeGame,setActiveGame]=useState(null),[error,setError]=useState(null);const fetching=useRef(false);const categories=[{id:'slots',name:'Slots',icon:'🎰'},{id:'live',name:'Live Casino',icon:'🎲'},{id:'sports',name:'Sports',icon:'⚽'},{id:'fishing',name:'Fishing',icon:'🎣'},{id:'lotto',name:'Lotto',icon:'🎱'}];
const fetchGames=async(params={})=>{if(fetching.current)return games;fetching.current=true;setLoading(true);setError(null);try{const data=await gameService.getGames(params);const list=extract(data);setGames(list);return list}catch(e){console.error('Fetch games error:',e);setError('Failed to load games. Please refresh.');setGames([]);return[]}finally{setLoading(false);fetching.current=false}};
const fetchProviders=async()=>{try{const d=await gameService.getProviders();const p=d?.providers||d?.list||[];setProviders(p);return p}catch(e){setProviders([]);return[]}};
const getGamesByCategory=async category=>{const list=await fetchGames({category});const normalized=String(category||'').toLowerCase();return list.filter(g=>g.category===normalized||!normalized)};
const searchGames=async q=>{const list=await fetchGames(q?.trim()?{search:q.trim()}:{});return list};
const getGamesByProvider=async provider=>fetchGames(provider?{provider}:{});
const toggleFavorite=id=>setFavorites(p=>{const n=p.includes(id)?p.filter(x=>x!==id):[...p,id];localStorage.setItem('favorites',JSON.stringify(n));return n});
useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem('favorites')||'[]'))}catch{}fetchGames();fetchProviders()},[]);
const value={games,providers,categories,loading,favorites,activeGame,error,fetchGames,fetchProviders,searchGames,getGamesByProvider,getGamesByCategory,toggleFavorite,isFavorite:id=>favorites.includes(id),setActiveGame,clearCache:()=>{clearGameCache();setGames([])}};return <GameContext.Provider value={value}>{children}</GameContext.Provider>};export default GameContext;