FROM node:18-alpine
WORKDIR /app
COPY frontend-admin/package.json ./
RUN npm install
COPY frontend-admin/ ./frontend-admin/
WORKDIR /app/frontend-admin
RUN npm run build
EXPOSE 4173
CMD ["npm","run","preview","--","--host","0.0.0.0","--port","4173"]
