import React, { useEffect, useState } from 'react';
import { FaCheck, FaTimes, FaSync, FaMoneyBillWave } from 'react-icons/fa';
import toast from 'react-hot-toast';
import superAdminApi from '../services/superAdminApi';
const money=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(v||0));
export default function SettlementCenter(){
 const [type,setType]=useState('all'),[rows,setRows]=useState([]),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null);
 const load=async()=>{setLoading(true);try{const [pending,s]=await Promise.all([superAdminApi.getPendingTransactions(type==='all'?{}:{type}),superAdminApi.getSettlementSummary()]);setRows(pending?.transactions||pending||[]);setSummary(s?.summary||s);}catch(e){toast.error('Unable to load settlement queue');}finally{setLoading(false)}};
 useEffect(()=>{load()},[type]);
 const settle=async(id,status)=>{if(!window.confirm(`${status==='completed'?'Approve':'Reject'} this transaction?`))return;setBusy(id);try{await superAdminApi.settleTransaction(id,status);toast.success(`Transaction ${status}`);load();}catch(e){toast.error(e.response?.data?.error||'Settlement failed')}finally{setBusy(null)}};
 const stat=(t,s)=>summary?.[t]?.[s]||{};
 return <div className="space-y-6 p-4 md:p-6"><header className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-[#111827] p-6 lg:flex-row lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-amber-400">Financial Operations</p><h1 className="text-2xl font-black text-white">Transaction Settlement Center</h1><p className="mt-1 text-sm text-slate-400">Review and settle pending player deposits and withdrawals with transactional backend controls.</p></div><button onClick={load} className="rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950"><FaSync className={loading?'animate-spin inline mr-2':'inline mr-2'}/>Refresh</button></header>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Pending Deposits',stat('deposit','pending')],['Completed Deposits',stat('deposit','completed')],['Pending Withdrawals',stat('withdraw','pending')],['Completed Withdrawals',stat('withdraw','completed')]].map(([n,v])=><div key={n} className="rounded-2xl border border-white/10 bg-[#111827] p-5"><div className="text-sm text-slate-400">{n}</div><div className="mt-2 text-2xl font-black text-white">{v.count||0}</div><div className="mt-1 text-xs text-amber-400">{money(v.total)} MMK</div></div>)}</div>
 <div className="flex gap-2"><button onClick={()=>setType('all')} className={`rounded-xl px-4 py-2 text-sm ${type==='all'?'bg-amber-400 font-bold text-slate-950':'border border-white/10 text-slate-300'}`}>All Pending</button><button onClick={()=>setType('deposit')} className={`rounded-xl px-4 py-2 text-sm ${type==='deposit'?'bg-amber-400 font-bold text-slate-950':'border border-white/10 text-slate-300'}`}>Deposits</button><button onClick={()=>setType('withdraw')} className={`rounded-xl px-4 py-2 text-sm ${type==='withdraw'?'bg-amber-400 font-bold text-slate-950':'border border-white/10 text-slate-300'}`}>Withdrawals</button></div>
 <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#111827]"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-white/[.03] text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">ID</th><th className="px-5 py-4">Player</th><th className="px-5 py-4">Type</th><th className="px-5 py-4">Amount</th><th className="px-5 py-4">Requested</th><th className="px-5 py-4 text-right">Settlement</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} className="border-t border-white/5"><td className="px-5 py-4 font-mono text-xs text-slate-500">#{r.id}</td><td className="px-5 py-4 font-bold text-white">{r.user_name||r.username||r.user_id}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs ${r.type==='deposit'?'bg-emerald-500/10 text-emerald-300':'bg-orange-500/10 text-orange-300'}`}>{r.type}</span></td><td className="px-5 py-4 font-bold text-white">{money(r.amount)} MMK</td><td className="px-5 py-4 text-slate-500">{r.created_at?new Date(r.created_at).toLocaleString():'-'}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button disabled={busy===r.id} onClick={()=>settle(r.id,'completed')} className="rounded-lg bg-emerald-500/15 px-3 py-1.5 text-xs text-emerald-300"><FaCheck className="inline mr-1"/>Approve</button><button disabled={busy===r.id} onClick={()=>settle(r.id,'rejected')} className="rounded-lg bg-red-500/10 px-3 py-1.5 text-xs text-red-300"><FaTimes className="inline mr-1"/>Reject</button></div></td></tr>):<tr><td colSpan="6" className="px-5 py-12 text-center text-slate-500">{loading?'Loading settlement queue…':'No pending transactions.'}</td></tr>}</tbody></table></div></div></div>}
