import toast from 'react-hot-toast';

export const capitalize = (str) => !str || typeof str !== 'string' ? '' : str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
export const truncate = (str, length = 50, suffix = '...') => !str || typeof str !== 'string' ? '' : (str.length <= length ? str : str.substring(0, length) + suffix);
export const formatNumber = (num) => num === undefined || num === null || Number.isNaN(Number(num)) ? '0' : Number(num).toLocaleString('en-US');
export const formatCurrency = (amount, currency = 'MMK') => {
  const value = Number(amount);
  const safe = Number.isFinite(value) ? value : 0;
  const code = String(currency || 'MMK').toUpperCase();
  const digits = code === 'MMK' ? 0 : 2;
  return `${safe.toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits})} ${code}`;
};
export const formatDate = (date, format = 'MMM DD, YYYY') => {if(!date)return'N/A';const d=new Date(date);if(Number.isNaN(d.getTime()))return'Invalid date';const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];const replacements={YYYY:d.getFullYear(),YY:String(d.getFullYear()).slice(2),MMM:months[d.getMonth()],MM:String(d.getMonth()+1).padStart(2,'0'),M:d.getMonth()+1,DD:String(d.getDate()).padStart(2,'0'),D:d.getDate(),ddd:days[d.getDay()],HH:String(d.getHours()).padStart(2,'0'),H:d.getHours(),mm:String(d.getMinutes()).padStart(2,'0'),ss:String(d.getSeconds()).padStart(2,'0')};let result=format;for(const[key,value]of Object.entries(replacements))result=result.replace(new RegExp(key,'g'),String(value));return result};
export const getRelativeTime=(date)=>{if(!date)return'N/A';const d=new Date(date);if(Number.isNaN(d.getTime()))return'Invalid date';const diff=Math.floor((new Date()-d)/1000);if(diff<60)return'Just now';if(diff<3600)return`${Math.floor(diff/60)}m ago`;if(diff<86400)return`${Math.floor(diff/3600)}h ago`;if(diff<604800)return`${Math.floor(diff/86400)}d ago`;if(diff<2419200)return`${Math.floor(diff/604800)}w ago`;if(diff<29030400)return`${Math.floor(diff/2419200)}mo ago`;return`${Math.floor(diff/29030400)}y ago`};
export const isEmpty=(value)=>value===null||value===undefined||(typeof value==='string'&&value.trim()==='')||(Array.isArray(value)&&value.length===0)||(typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===0);export const isValidEmail=email=>!!email&&typeof email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);export const isValidUrl=url=>{try{new URL(url);return true}catch{return false}};export const isMobile=()=>window.innerWidth<768;export const isTablet=()=>window.innerWidth>=768&&window.innerWidth<1024;export const isDesktop=()=>window.innerWidth>=1024;export const copyToClipboard=async text=>{try{await navigator.clipboard.writeText(text);toast.success('Copied to clipboard');return true}catch{toast.error('Failed to copy');return false}};export const deepClone=obj=>obj===null||typeof obj!=='object'?obj:Array.isArray(obj)?obj.map(deepClone):Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,deepClone(v)]));export const groupBy=(array,key)=>Array.isArray(array)?array.reduce((result,item)=>{const groupKey=typeof key==='function'?key(item):item[key];(result[groupKey]??=[]).push(item);return result},{}):{};export const sortBy=(array,key,ascending=true)=>{if(!Array.isArray(array))return[];return[...array].sort((a,b)=>{let av=typeof key==='function'?key(a):a[key],bv=typeof key==='function'?key(b):b[key];if(typeof av==='string')av=av.toLowerCase();if(typeof bv==='string')bv=bv.toLowerCase();return av<bv?(ascending?-1:1):av>bv?(ascending?1:-1):0})};export default{capitalize,truncate,formatNumber,formatCurrency,formatDate,getRelativeTime,isEmpty,isValidEmail,isValidUrl,isMobile,isTablet,isDesktop,copyToClipboard,deepClone,groupBy,sortBy};
