import React, { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import slotAudio from '../../services/slotAudio';

const unwrapSymbol = (value) => {
  if (value && typeof value === 'object') return value.symbol ?? value.sym ?? value.id ?? value.value ?? value.code ?? value.name ?? '?';
  return value;
};

const symbolLabel = (value) => {
  const v = unwrapSymbol(value);
  if (v === null || v === undefined) return '·';
  return String(v);
};

const symbolKind = (value) => {
  const text = symbolLabel(value).toLowerCase();
  if (text.includes('wild')) return 'wild';
  if (text.includes('scatter')) return 'scatter';
  if (text.includes('bonus')) return 'bonus';
  return 'normal';
};

const normalizeGrid = (grid) => {
  if (!Array.isArray(grid) || !grid.length) return [];
  const rows = Array.isArray(grid[0]) ? grid : [grid];
  const width = Math.max(...rows.map((r) => Array.isArray(r) ? r.length : 1));
  const height = rows.length;
  // Slotopol responses can be represented as rows or reels. Use metadata
  // dimensions when supplied by the server to avoid inventing reel layouts.
  return { rows, width, height };
};

const getWinningKeys = (wins, width, height) => {
  const keys = new Set();
  (Array.isArray(wins) ? wins : []).forEach((win) => {
    const positions = win?.positions || win?.cells || win?.coords || win?.coordinates;
    if (Array.isArray(positions)) {
      positions.forEach((p) => {
        if (Array.isArray(p) && p.length >= 2) keys.add(`${p[0]}:${p[1]}`);
        else if (p && typeof p === 'object') keys.add(`${p.row ?? p.y ?? 0}:${p.col ?? p.x ?? 0}`);
      });
    }
    const line = win?.line ?? win?.payline;
    if (Array.isArray(line)) line.forEach((row, col) => keys.add(`${row}:${col}`));
  });
  if (!keys.size && Array.isArray(wins) && wins.length) return null;
  return keys;
};

export default function SlotReelBoard({ grid, wins = [], spinning = false, sound = true, reels = 0, rows = 0 }) {
  const normalized = useMemo(() => normalizeGrid(grid), [grid]);
  const [phase, setPhase] = useState(0);

  useEffect(() => {
    if (!spinning) return undefined;
    setPhase((p) => p + 1);
    if (sound) slotAudio.spinStart();
    return undefined;
  }, [spinning, sound]);

  if (!normalized) {
    return (
      <div className="relative w-full max-w-5xl aspect-[16/8] min-h-[280px] rounded-3xl bg-black/40 border border-white/10 flex items-center justify-center overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(245,158,11,.12),transparent_58%)]" />
        <div className="text-center text-slate-400">
          <div className="text-4xl mb-3">◈</div>
          <div className="font-semibold">Waiting for Slotopol game state</div>
          <div className="text-xs mt-1">The reel layout will use the dimensions returned by the server.</div>
        </div>
      </div>
    );
  }

  const rowCount = rows || normalized.height;
  const colCount = reels || normalized.width;
  const winning = getWinningKeys(wins, colCount, rowCount);
  const cells = [];

  // Render the response exactly as received. No local RNG or local win result
  // is generated by this component.
  normalized.rows.forEach((row, r) => {
    const values = Array.isArray(row) ? row : [row];
    values.forEach((value, c) => cells.push({ value, r, c }));
  });

  return (
    <div className="relative w-full max-w-5xl">
      <div className="absolute -inset-1 rounded-[28px] bg-gradient-to-r from-amber-400/20 via-fuchsia-500/10 to-amber-400/20 blur-xl" />
      <div className="relative rounded-3xl border border-amber-300/20 bg-[#080b14] p-2 sm:p-3 md:p-5 shadow-[0_25px_80px_rgba(0,0,0,.55)] overflow-hidden">
        <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500" />
        <div className="absolute inset-x-0 top-0 h-20 bg-gradient-to-b from-white/[.06] to-transparent pointer-events-none" />
        <div className="relative grid gap-1.5 sm:gap-2 md:gap-3" style={{ gridTemplateColumns: `repeat(${colCount}, minmax(0, 1fr))` }}>
          {cells.map(({ value, r, c }) => {
            const key = `${r}:${c}`;
            const isWin = winning === null || winning?.has(key);
            const kind = symbolKind(value);
            return (
              <motion.div
                key={`${phase}-${key}`}
                initial={{ y: spinning ? -32 - c * 7 : 0, opacity: spinning ? 0.45 : 1, scale: 0.96 }}
                animate={{ y: 0, opacity: 1, scale: isWin && !spinning ? 1.03 : 1 }}
                transition={{ duration: spinning ? 0.22 + c * 0.035 : 0.18, delay: spinning ? c * 0.04 : 0, ease: 'easeOut' }}
                onAnimationComplete={() => {
                  if (sound && spinning && r === rowCount - 1) slotAudio.reelStop(c);
                }}
                className={`relative aspect-square min-h-[58px] sm:min-h-[84px] md:min-h-[108px] rounded-xl overflow-hidden border flex items-center justify-center select-none ${
                  isWin && !spinning ? 'border-amber-300/80 shadow-[0_0_24px_rgba(251,191,36,.28)]' : 'border-white/10'
                } ${kind === 'wild' ? 'bg-gradient-to-br from-fuchsia-700/70 to-violet-950' : kind === 'scatter' ? 'bg-gradient-to-br from-amber-600/70 to-orange-950' : kind === 'bonus' ? 'bg-gradient-to-br from-emerald-600/60 to-cyan-950' : 'bg-gradient-to-b from-slate-700/95 via-slate-800 to-slate-950'}`}
              >
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_25%,rgba(255,255,255,.12),transparent_45%)]" />
                <div className="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-black/30 to-transparent" />
                <span className={`relative z-10 font-black tracking-tight text-center leading-none break-all px-1 ${String(value ?? '').length > 7 ? 'text-[clamp(12px,2vw,22px)]' : 'text-[clamp(18px,4vw,42px)]'} ${isWin && !spinning ? 'text-amber-100' : 'text-white'}`}>
                  {symbolLabel(value)}
                </span>
                {isWin && !spinning && (
                  <motion.span initial={{ opacity: 0, scale: .5 }} animate={{ opacity: [0, 1, 0], scale: [0.7, 1.2, 1.45] }} transition={{ duration: .75 }} className="absolute inset-0 border-2 border-amber-300 rounded-xl pointer-events-none" />
                )}
              </motion.div>
            );
          })}
        </div>
        <div className="mt-2 flex items-center justify-between text-[9px] sm:text-[11px] uppercase tracking-[.18em] text-slate-500">
          <span>Server result</span>
          <span>{colCount} × {rowCount}</span>
        </div>
      </div>
    </div>
  );
}
