import React,{useEffect,useState}from'react';
import{Routes,Route,Navigate,Link}from'react-router-dom';
import{useAuth}from'./auth';
import api from'./api';
import{FaBars,FaUsers,FaMoneyBillWave,FaExchangeAlt,FaGamepad,FaChartBar,FaSignOutAlt,FaTachometerAlt}from'react-icons/fa';

const CURRENCY='MMK';
const formatMoney=value=>`${Number(value||0).toLocaleString('en-US',{maximumFractionDigits:2})} ${CURRENCY}`;
function Guard({children}){const a=useAuth();if(a.loading)return <div className="center">Loading…</div>;return a.isAuthenticated?children:<Navigate to="/login" replace/>}
function Layout({children}){const a=useAuth(),[open,setOpen]=useState(false);const links=[['/','Dashboard',FaTachometerAlt],['/users','Users',FaUsers],['/deposits','Deposits',FaMoneyBillWave],['/withdrawals','Withdrawals',FaExchangeAlt],['/transactions','Transactions',FaExchangeAlt],['/games','Games',FaGamepad],['/reports','Reports',FaChartBar]];return <div className="shell"><aside className={open?'open':''}><div className="brand">N999<span>Bet</span><small> Employee Admin · Myanmar / MMK</small></div>{links.map(([p,n,I])=><Link key={p} to={p} onClick={()=>setOpen(false)}><I/> {n}</Link>)}<button className="logout" onClick={a.logout}><FaSignOutAlt/> Logout</button></aside><main><header><button className="menu" onClick={()=>setOpen(!open)}><FaBars/></button><div><b>N999Bet Employee Panel</b><small>{a.user?.username} · {a.user?.role} · Myanmar / MMK</small></div></header><section className="content">{children}</section></main></div>}
function Login(){const a=useAuth(),[u,setU]=useState(''),[p,setP]=useState(''),[err,setErr]=useState('');if(a.isAuthenticated)return <Navigate to="/" replace/>;return <div className="login"><form onSubmit={async e=>{e.preventDefault();setErr('');try{await a.login(u,p)}catch(x){setErr(x.response?.data?.error||x.message||'Login failed')}}}><h1>N999<span>Bet</span></h1><h2>Employee Admin</h2><small>Myanmar / MMK</small>{err&&<div className="error">{err}</div>}<input value={u} onChange={e=>setU(e.target.value)} placeholder="Username" required/><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Password" required/><button>Sign in</button></form></div>}
function Table({columns,rows}){return <div className="tablewrap"><table><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c[0]}>{typeof c[2]==='function'?c[2](r):r[c[0]]??'—'}</td>)}</tr>):<tr><td colSpan={columns.length} className="empty">No records</td></tr>}</tbody></table></div>}
function Dashboard(){const [data,setData]=useState({users:0,transactions:0,pending:0,deposits:0,withdrawals:0});useEffect(()=>{api.get('/employee/dashboard').then(r=>setData(r.data.stats||{})).catch(()=>{})},[]);return <><h1>Dashboard</h1><div className="cards"><Card t="Visible users" v={data.users}/><Card t="Pending approvals" v={data.pending}/><Card t="Completed deposits" v={data.deposits}/><Card t="Completed withdrawals" v={data.withdrawals}/></div><Panel title="Myanmar / MMK employee operations"><p>Customer financial actions are processed in N999Bet. Slotopol provider credit is separate and is not treated as a customer wallet.</p></Panel></>}
function Card({t,v}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
function Panel({title,children}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Users(){const [rows,setRows]=useState([]),[q,setQ]=useState('');const load=()=>api.get('/employee/users',{params:{search:q,limit:100}}).then(r=>setRows(r.data.users||[]));useEffect(()=>{load()},[]);return <><div className="title"><h1>Users</h1><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search users"/><button onClick={load}>Refresh</button></div><Table rows={rows} columns={[['id','ID'],['username','Username'],['email','Email'],['status','Status'],['role','Role'],['created_at','Created'],['actions','Actions',(r)=><button onClick={async()=>{const s=r.status==='active'?'suspended':'active';await api.put(`/employee/users/${r.id}/status`,{status:s});load()}}>{r.status==='active'?'Suspend':'Activate'}</button>]]}/></>}
function Transactions({filter}){const [rows,setRows]=useState([]);const load=()=>api.get('/employee/transactions?limit=100').then(r=>setRows((r.data.transactions||[]).filter(x=>!filter||x.type===filter)));useEffect(()=>{load()},[filter]);const act=async(id,ok)=>{await api.put(`/employee/transactions/${id}/${ok?'approve':'reject'}`);load()};return <><div className="title"><h1>{filter==='deposit'?'Deposits':filter==='withdraw'?'Withdrawals':'Transactions'}</h1><button onClick={load}>Refresh</button></div><Table rows={rows} columns={[['id','ID'],['user_id','User'],['type','Type'],['amount','Amount',r=>formatMoney(r.amount)],['status','Status'],['created_at','Created'],['actions','Actions',r=>r.status==='pending'?<><button className="ok" onClick={()=>act(r.id,true)}>Approve</button><button className="danger" onClick={()=>act(r.id,false)}>Reject</button></>:'—']]}/></>}
function Games(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/games').then(r=>setRows(r.data.games||[])).catch(()=>setRows([]))},[]);return <><h1>Games</h1><Panel title="Provider game visibility"><p>Slotopol controls which games are provided to N999Bet. This employee panel is read-only for provider permissions.</p></Panel><Table rows={rows} columns={[['id','Game ID'],['name','Name'],['provider','Provider'],['category','Category'],['isActive','Status',r=><span className={r.isActive?'status ok':'status danger'}>{r.isActive?'Active':'Disabled'}</span>],['minBet','Min bet',r=>formatMoney(r.minBet)],['maxBet','Max bet',r=>formatMoney(r.maxBet)]]}/></>}
function Reports(){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/employee/transactions?limit=100').then(r=>setRows(r.data.transactions||[])).catch(()=>setRows([]))},[]);const total=rows.reduce((s,r)=>s+(r.type==='deposit'?Number(r.amount):r.type==='withdraw'?-Number(r.amount):0),0);return <><h1>Reports</h1><div className="cards"><Card t="Loaded records" v={rows.length}/><Card t="Deposit minus withdrawal" v={formatMoney(total)}/></div><Panel title="Audit note"><p>Reports shown here are derived from N999Bet transaction records. Provider balances are not treated as customer balances. Currency: MMK.</p></Panel></>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="*" element={<Guard><Layout><Routes><Route path="/" element={<Dashboard/>}/><Route path="/users" element={<Users/>}/><Route path="/deposits" element={<Transactions filter="deposit"/>}/><Route path="/withdrawals" element={<Transactions filter="withdraw"/>}/><Route path="/transactions" element={<Transactions/>}/><Route path="/games" element={<Games/>}/><Route path="/reports" element={<Reports/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Layout></Guard>}/></Routes>}
